### ISSUE TITLE
Bot pings insane large number of authors for new module requests

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/collection_bot#18]
See for example https://github.com/ansible-collections/community.general/pull/876#issuecomment-745602176

I'm not sure how it determines that long author list, I guess it's somehow looking at *all* modules becaues of the symlink in plugins/modules/.

In any case, such long CC lists are really annoying - for both the people pinged there, and for other people in the PR.

**Comment by gundalow** [comment]
Should be fixed by https://github.com/ansible-community/collection_bot/pull/19
